### ISSUE TITLE
¿este proyecto tiene un calendario para reservar un turno en el hospital?

### ISSUE THREAD

**Issue by jmr85** [luisr-carrillo/ng-hospital-admin-front#8]

**Comment by luisr-carrillo** [comment]
Hola. 

El proyecto fue solamente de practica. Se realizó con el curso de Angular Avanzado por Fernando Herrera (@Klerith) en Udemy. No incluye ningún calendario y está algo sencilla la aplicación, tendrías que hacer los cambios que desees para que se adapte a alguna necesidad que tengas.

**Comment by jmr85** [comment]
Buenisimo, gracias por responder. Si estoy haciendo el curso de Angular de cero a experto... y espero tambien  completar el de angular avanzado que es este proyecto. Si tengo pensado agregar un calendario, tal vez usar componente calendar de NgPrime. Saludos
